# Generated by Django 4.2 on 2023-05-01 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='document_storage.document')),
            ],
            bases=('document_storage.document',),
        ),
        migrations.AlterField(
            model_name='document',
            name='versions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_versions', to='document_storage.documentversion'),
        ),
    ]
