# Generated by Django 4.2 on 2023-05-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_storage', '0002_documentversion_alter_document_versions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='versions',
        ),
        migrations.AddField(
            model_name='documentversion',
            name='versions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_versions', to='document_storage.document'),
        ),
    ]
